### ISSUE TITLE
Getting error message from pull request

### ISSUE THREAD

**Issue by darias08** [bdeguigne/Game-Bringer#54]
Hello!

I am trying to understand how you were able to set up the `BestRatedGames` in your request from IGDB? Like, I tried to implement your code into mine, but I am getting an error message saying "Undefined is not a function". When I try to call/set the data to my app. 

This is where I am getting your code from: 
https://github.com/bdeguigne/Game-Bringer/blob/f80277f17c752f1afb6134cb68ee2df57ae416de/src/redux/services/homePageRequestsServices.js#L42-L58

I am using that exact same code and using this as my pull request code: 
```
getBestRatedGamesRequest().then(response => {
        console.log(response.data);
        })
        .catch(err => {
            console.error(err);
        }),
```

It's saying after .then() I am getting the error message. Anyway I can fix this problem?

**Comment by bdeguigne** [comment]
Hello !

.then() will not work if your function do not return a promise. So I think there is an error inside the `doRequest` function. 
I'm using this because I was getting some errors when i tried to deploy my app with Netlify. But if you want to test on your side maybe it will be simpler if you just do a request to the IGDB API ?

I was using this before moving to Netlify :

```
export const doRequest = (url, data) => {
    var myHeaders = new Headers();
    myHeaders.append("Client-ID", "{{YOUR_CLIENT_ID}}");
    myHeaders.append("Authorization", "Bearer {{YOUR_BEARER_TOKEN}}");
    myHeaders.append("Content-Type", "text/plain");
    myHeaders.append("Access-Control-Allow-Origin", "*");

    var requestOptions = {
        method: 'POST',
        headers: myHeaders,
        body: data,
        redirect: 'follow'
    };

    return (fetch(url, requestOptions))
}
```

And then, you need to call this function like this for the `bestRatedGames`:

`doRequest("https://api.igdb.com/v4/games", query);`

Good luck !

**Comment by darias08** [comment]
For some reason I am able to pull the other pull request like most_anticipated_games, popular now, etc.. But only this one I can't seem to make a request.

**Comment by darias08** [comment]
![pull request](https://user-images.githubusercontent.com/58616895/206780994-1c5b4cfb-62a9-4665-a717-0eab2de4277c.PNG)

Here's a screenshot of what I have set to

**Comment by bdeguigne** [comment]
Do you have any error in the console or in the network panel ?

**Comment by darias08** [comment]
Here's what I am getting from the console log

![Promise Unhandle error](https://user-images.githubusercontent.com/58616895/206786291-2a19eb35-2113-4b59-8118-3ab2230cb922.PNG)

When I hover over bestRatedGames I get this message: 

` (alias) const getBestRatedGamesRequest: (time: any) => false | undefined import getBestRatedGamesRequest`

![list of request](https://user-images.githubusercontent.com/58616895/206786573-eca8dacf-7ab9-4e90-83a9-9a159a27af11.PNG)

I believe it has something to do with the parameter for time. Do you know what it's used for? I believe that's why it's throwing an error message saying it's undefined.

**Comment by bdeguigne** [comment]
It's an enum. It's just a simple string that I passed in parameter in order to trigger the condition. It can be anything.

**Comment by darias08** [comment]
Could you show me where you passed that?

**Comment by bdeguigne** [comment]
Here : 

https://github.com/bdeguigne/Game-Bringer/blob/52f3100657f691639fd561d6671b0caea7f2acfc/src/App.js#L34.

`bestRatedGames.THIS_MONTH` is equal to the string : "BEST_RATED_GAMES_THIS_MONTH"
