### ISSUE TITLE
Question about home page/top rate games

### ISSUE THREAD

**Issue by darias08** [bdeguigne/Game-Bringer#55]
Hello!

I am browsing through your homepage.js file and I am trying to understand how you were able to pass the data from the `HomePage` to `TopRatedGames` when you haven't passed any params on the component? Here it's just showing `<TopRatedGames/>` and nothing else being passed.
https://github.com/bdeguigne/Game-Bringer/blob/f80277f17c752f1afb6134cb68ee2df57ae416de/src/components/HomePage.js#L63

Like here in your `TopRatedGames.js` component I am seeing you are using `games` as your param, but I am just confused on where it's coming from or how it's being used? 
https://github.com/bdeguigne/Game-Bringer/blob/f80277f17c752f1afb6134cb68ee2df57ae416de/src/components/TopRatedGames.js#L108

**Comment by darias08** [comment]
Also could you help me to explain what is the difference between `GameDetails` and `GameShowCase`? They almost seem identical for showing the game data when you click on a game image, but I am trying to understand how the data is being passed from.

Like what is the `GameDetails`? Where is this being passed from as a component?

**Comment by bdeguigne** [comment]
Hey ! 

For your first question that's because I'm using a state manager called [Redux](https://react-redux.js.org/). If you don't know what that is, it's basically a way to share and access all of your data accross your component more easily.

I let you a link to the documentation of the [mapStateToProps](https://react-redux.js.org/using-react-redux/connect-mapstate) because this allows me to connect my component to the store (this is where I'm storing my data) and access them in my componenent without passing them as props.

A state manager it's a really usefull tool that you should use. Once your project gets bigger and bigger, a state manager becomes essential and once you get used to it, you can't live without it.

**Comment by bdeguigne** [comment]
- `GameShowCase` is the middle section of the homepage with the "Top rating games this month" title. 
- `GameDetails` is the page that is shown when you click on a game.

`GameDetails` is a whole new page so it's called a little bit differently actually. It is called inside the `src/routes.js`

https://github.com/bdeguigne/Game-Bringer/blob/f80277f17c752f1afb6134cb68ee2df57ae416de/src/routes.js#L5-L13

So, here you can see the differents **routes** of this app. When I'm navigating to : `https://game-bringer.netlify.app/{id}/{gameName}` it's automatically calling the `GameDetails` component.

With this, I can get the id and gameName variable inside the url to fetching the data that I need to display in my component.

I'm using the [react-router](https://reactrouter.com/en/main/start/overview) library for managing my routes. It's a very usefull stuff too.

I hope to have helped you with my answers, I also guided you towards two very useful tools which are [react redux](https://react-redux.js.org/) and [react router](https://reactrouter.com/en/main/start/overview), I leave you towards their documents which will be surely much more useful than me, but if you have specific questions on these subjects or other questions do not hesitate, I would be a pleasure to help you

**Comment by darias08** [comment]
Hello @bdeguine!

Thank you for your response! I'll definitely take a look at using Redux and try to use that as well on my project. I want to ask you a little bit more about the navigation with data. 

So there is a button you have that says `See more` which you were saying that will be the `GameDetails` page. I am looking at the function you used which is `onClick`  

https://github.com/bdeguigne/Game-Bringer/blob/f80277f17c752f1afb6134cb68ee2df57ae416de/src/components/SimpleCard.js#L83

Could you explain to me how this function is being used here? Just so I can get a deeper understanding and how it works.

Thank you so much for taking the time to help me with this! It means so much to me and I can't thank you enough! :D ^-^

**Comment by bdeguigne** [comment]
No problem !

So if I understand your question correctly, inside of the `onClick` I'm using `history.replace` wich allows me to replace the url and navigate to a different page.

Here i'm passing the **path** of my route :

https://github.com/bdeguigne/Game-Bringer/blob/f80277f17c752f1afb6134cb68ee2df57ae416de/src/components/SimpleCard.js#L85

> Inside of `src/routes.js`, I defined my route to `GameDetails` like this : `path: "/:id/:name/"`.

As you can see, I just follow the same path : I'm taking the game Id with `game.id` and the game name correspond to my `urlTitle` which is defined just above.

For exemple, at the end the url look like this : `/152242/A_Plague_Tale:_Requiem`.

As I set the path: `/:id/:name/` to point to the GameDetails component, when I navigate to it, it automatically calls my component !

I hope its clear, let me know if not !

Good luck !

**Comment by bdeguigne** [comment]
P.S : If you are using redux, I recommand you to use the [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=fr) extension. Which is very usefull for debugging.

**Comment by darias08** [comment]
Oh okay! I see now. I was confused as to how you were able to navigate each screen but I didn't know you have a routes section lol. I'll definitely use `Redux DevTools` as well which will help a lot with my project. Anyways, thank you so much for your help bdeguine!! This is all I need help with and thank you for taking the time to help me with this! ^-^

**Comment by darias08** [comment]
Hi bdeguine!

I just want to let you know the redux is really helping a lot! ^-^ It really solved a lot of my problems with my application and has made things a lot easier for me. Anyways, there is one issue I am having trouble getting to work. I am trying to hide the `developer` title and supplant it with the publisher instead. I am seeing in your `GameInfo.js` you use something like `isEmpty` could you elaborate what that means? I know that there are some games that don't have developer and it's just the publisher only. Please let me know what do you think and I will be happy to hear your advice!

Thanks! :)

https://github.com/bdeguigne/Game-Bringer/blob/f80277f17c752f1afb6134cb68ee2df57ae416de/src/components/Game%20details/GameInfo.js#L80
